### ISSUE TITLE
Not working at the moment

### ISSUE THREAD

**Issue by uesu** [auribuo/hsr-alert-bot#1]
Is it still "Work in Progress" state? Can't enable alerts and has internal error

**Comment by auribuo** [comment]
Yes, the bot is still in experimental phase. 
It started as a handy thing for myself but it seems that the bot is actually getting attention.

The error seems a failure in retrieving guild information and I will look into it and try to fix it.

**Comment by uesu** [comment]
I see, no worries tho, please do update me if it's fixed! also you can upload your bot on [top.gg](https://top.gg/tag/honkai) for more exposure

**Comment by auribuo** [comment]
I made some changes to the config code. Try again and let me know if the issue persists!

**Comment by uesu** [comment]
I tested it, hmm still can't, tried on public and private, same issue

![2024-02-15 06_10_19-(654) Discord _ Permissions _ jieun's publishing house](https://github.com/auribuo/hsr-alert-bot/assets/39020293/69f74910-d45b-4a5b-ae52-b181143438d0)
![2024-02-15 06_10_14-(654) Discord _ Permissions _ jieun's publishing house](https://github.com/auribuo/hsr-alert-bot/assets/39020293/f5af392d-287a-4a7d-b4cc-4f8c70fd0aa9)
![2024-02-15 06_10_01-(654) Discord _ #hsr-codes _ jieun's publishing house](https://github.com/auribuo/hsr-alert-bot/assets/39020293/606cb280-e464-446a-b0a5-2eda9e0e30da)

**Comment by auribuo** [comment]
From the logs, it looks like the bot could not resolve guild information. It probably happens because in its current state, the bot updates the config only on code retrieval. I will update the code tomorrow to account for this. It will probably be a bandaid fix until I find the event handler for when the bot joins a server. Illtry to restart the bot to force an update and force your server into the config.

**Comment by uesu** [comment]
Oh I see, no worries, I'm happy to help and provide feedback to make sure everything is working for everyone who uses your bot to be 100% working. Do update me

**Comment by auribuo** [comment]
Issue should be fixed now. The bot checks on every interaction if the guild is in the config so it should update instantly. Try it out and let me know!

**Comment by uesu** [comment]
I just checked, and it's working now, thank you! I will notify you if the bot sends a code when there is a new code

![2024-02-15 18_48_12-(644) Discord _ #hsr-codes _ jieun's publishing house](https://github.com/auribuo/hsr-alert-bot/assets/39020293/37562d5b-28e5-4629-95e0-555fd219e27b)

Suggestion: A feature to get codes that are still fresh or those codes that do not expire, it may be called manual to get codes manually?

Also, is the code like the link that takes you to the gift website and automatically inputs the code? Like this

![2024-02-15 19_05_28-(645) Discord _ #genshin-codes _ jieun's publishing house](https://github.com/auribuo/hsr-alert-bot/assets/39020293/4ff57573-3500-4e85-9bb7-56f150bf7965)
![2024-02-15 19_05_40-(645) Discord _ #genshin-codes _ jieun's publishing house](https://github.com/auribuo/hsr-alert-bot/assets/39020293/5630050b-3e42-4ff5-9fb8-8d258f94eac1)

Also again, for gathering codes, include this website if you haven't already, [Prydwen](https://www.prydwen.gg/), which shows the active codes or those codes that do not expire

![2024-02-15 18_51_03-Honkai_ Star Rail Wiki and Database _ Prydwen Institute](https://github.com/auribuo/hsr-alert-bot/assets/39020293/0636e231-c8c9-43ca-b813-04cf2672911f)

Also!! hmm will there be a Genshin Impact and Zenless Zone Zero code bot in the future? Alternatively, it could be all in one bot for the three Hoyoverse games! I've never seen a bot with the three games feature for codes or like news yet before

**Comment by auribuo** [comment]
I'm happy to hear that the issue was solved. For the features you mentioned I opened two new issues: #2 and #3 to track progress on those features.

**Comment by uesu** [comment]
Thanks! no rush, but it would be cool indeed to have those additional 2

> I'm happy to hear that the issue was solved. For the features you mentioned I opened two new issues: #2 and #3 to track progress on those features.

**Comment by uesu** [comment]
> I'm happy to hear that the issue was solved. For the features you mentioned I opened two new issues: #2 and #3 to track progress on those features.

There's a new code by the way on the livestream today 2.1, it did not send yet nor the previous ones recent ones

SB87P52BTVQ3

2.1
#1 - 3SRN6L3AADLK
#2 - YTRN743TSUL7 
#3 - 2S8N6M3ATV6T
