### ISSUE TITLE
No code yet sent/published by the herta bot

### ISSUE THREAD

**Issue by uesu** [auribuo/hsr-alert-bot#5]
There's a new code by the way on the livestream today 2.1, it did not send yet nor the previous one (the recent)

(recent previous one)
SB87P52BTVQ3

2.1
- 3SRN6L3AADLK
- YTRN743TSUL7 
- 2S8N6M3ATV6T

**Comment by auribuo** [comment]
The bot sent the codes into my server so the scraping works just fine. Looking at the logs it seems like it has some issues resolving the guild ids. Can you send me the server id of the server you are in so I can double check it?

**Comment by uesu** [comment]
> The bot sent the codes into my server so the scraping works just fine. Looking at the logs it seems like it has some issues resolving the guild ids. Can you send me the server id of the server you are in so I can double check it?

Sorry for the late response, I see, no worries

Here is the channel ID for the bot assigned to send the message: 1204241533797142578

Server ID: 901452434377953300

**Comment by auribuo** [comment]
Looks like something is really off. It looks like the codes were sent and after there is an error regarding no alert channel being set. Sadly I cannot inspect the config file holding the Information because of the deployment environment. I'll try to attach the bot to a DB instance instead of using a file. It should be also more scalable in the future.

**Comment by uesu** [comment]
I see it was sent, but there is an error despite the fact that the channel and alert are set, and I have already activated permissions for almost all possible permissions. Let me know or update me if it's fixed no rush and if there's anything I need to do, such as reactivating the slash commands to set it up again

![2024-03-17 07_06_19-(1) Discord _ #hsr-codes _ jieun's publishing house](https://github.com/auribuo/hsr-alert-bot/assets/39020293/0069f2f6-2344-4d27-aa74-d6e3b97137c0)

**Comment by auribuo** [comment]
I changed the code to use a Db and did some improvements in general. Let me know if the bot now works for you as expected.

**Comment by uesu** [comment]
> I changed the code to use a Db and did some improvements in general. Let me know if the bot now works for you as expected.

Alright, should I do the / slash commands again or no need? And since there are no new codes yet, but there might be later due to the new update, we'll see

**Comment by auribuo** [comment]
Try the slash commands again. You should actually get a bunch of new codes because the bot "forgot" which were already sent.

**Comment by uesu** [comment]
> Try the slash commands again. You should actually get a bunch of new codes because the bot "forgot" which were already sent.

![2024-03-27 16_09_16-(12) Discord _ #hsr-codes _ jieun's publishing house](https://github.com/auribuo/hsr-alert-bot/assets/39020293/083de145-0f09-4acf-ac6b-0ef0f53da680)

I see and yup also thanks, did few hours/mins ago and it finally shows up now, It's fully working
