### ISSUE TITLE
Duplicates?

### ISSUE THREAD

**Issue by uesu** [auribuo/hsr-alert-bot#6]
I can see it's working now thanks once again, but there were new codes and i'm not sure if this is normal

MOREPEACH
HSR1YEAR
0327CARNIVAL

Instead, it shows the same 3 codes

![2024-03-28 07_44_38-#hsr-codes _ jieun's publishing house - Discord](https://github.com/auribuo/hsr-alert-bot/assets/39020293/30af3998-d27a-426c-bbf7-7f142061e2e5)

**Comment by auribuo** [comment]
Was a bug, should already be fixed.
