### ISSUE TITLE
Can’t invite bot

### ISSUE THREAD

**Issue by notfence** [auribuo/hsr-alert-bot#9]
Hello! Can you fix this? I can’t invite bot to any server. Can you somehow make the bot verified? Or make instructions on how to build bot myself? Thanks!
![IMG_0050](https://github.com/user-attachments/assets/09a6317b-7d98-469f-9721-c98e2f6d7efa)

**Comment by auribuo** [comment]
Hi, 
weird that it does not work, the bot should not have intents active. Anyway, I'm going to look into the issue and let you know when It's fixed.

**Comment by auribuo** [comment]
I verified the app. The issue should be fixed. Lmk if it works now

**Comment by notfence** [comment]
Yep! Everything works great, thanks!
